# Generated by Django 3.2.7 on 2021-09-19 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', validators=[images.validators.validate_extension])),
                ('thumbnail_200', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('thumbnail_400', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomImageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_height', models.IntegerField()),
                ('custom_name', models.CharField(blank=True, editable=False, max_length=50)),
                ('custom_thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='images/')),
                ('image_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imageapi')),
            ],
        ),
    ]
