# Generated by Django 3.2.7 on 2021-09-19 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimagesize',
            name='image_api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_thumbnails', to='images.imageapi'),
        ),
    ]
